env:
  browser: true
  node: true
  commonjs: true
  es6: true
  mocha: true
extends:
- standard
- standard-react
- plugin:import/errors
- plugin:import/warnings
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
- import
settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules
      - src
rules:
  comma-dangle:
  - error
  - always-multiline
  no-duplicate-imports:
  - off
  import/no-duplicates:
  - error
  - always
